# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 15:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0002_auto_20170314_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('question_and_answer', wagtail.wagtailcore.blocks.StructBlock((('question', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=True)), ('answer', wagtail.wagtailcore.blocks.RichTextBlock())))))),
        ),
    ]
