# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 09:35
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170316_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(max_length=1000),
        ),
    ]
