# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 11:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_eventpage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='date_time',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='end_time',
            field=models.TimeField(default='17:00', verbose_name='Ends'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='start_time',
            field=models.TimeField(default='17:00', verbose_name='Starts'),
        ),
    ]
