# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170316_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='start_time',
            field=models.TimeField(default='10:00', verbose_name='Starts'),
        ),
    ]
