# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:08
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170320_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
