# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventpage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='intro',
        ),
    ]
