# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_eventpagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
