# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 12:06
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ourresearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourresearchindex',
            name='intro_index',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
