# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourresearch', '0002_ourresearchindex_intro_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourresearchindex',
            name='subject',
        ),
        migrations.AddField(
            model_name='ourresearchsubject',
            name='fa_icon_subject',
            field=models.CharField(default='fa-', max_length=255),
        ),
    ]
