# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('ourresearch', '0002_ourresearcharticle_ourresearchgalleryimage_ourresearchsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourresearcharticle',
            name='image_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='ourresearcharticle',
            name='image_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
