# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 10:19
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ourresearch', '0004_auto_20170315_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourresearchindex',
            name='subject',
            field=wagtail.wagtailcore.fields.StreamField((('subject_thumb', wagtail.wagtailcore.blocks.StructBlock((('fa_icon', wagtail.wagtailcore.blocks.CharBlock(default='fa-', max_length=255, required=True)), ('fa_icon_size', wagtail.wagtailcore.blocks.ChoiceBlock(choices=['fa-lg', 'fa-2x', 'fa-3x', 'fa-4x', 'fa-5x'], required=False)), ('caption', wagtail.wagtailcore.blocks.CharBlock(default='', max_length=255, required=True))))),), default=0),
            preserve_default=False,
        ),
    ]
