# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:05
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ourresearch', '0011_auto_20170322_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourresearchindex',
            name='subject',
        ),
        migrations.AddField(
            model_name='ourresearchindex',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
