# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 07:54
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0002_auto_20170404_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('section_heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('sub_section_heading', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()))),
        ),
    ]
