# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 15:01
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20170405_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('About', wagtail.wagtailcore.blocks.StructBlock((('section_heading', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=True)), ('text', wagtail.wagtailcore.blocks.RichTextBlock())))),), null=True),
        ),
    ]
