# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0002_auto_20170313_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='uni',
            field=models.CharField(max_length=255),
        ),
    ]
