# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0004_auto_20170321_0927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventPageGalleryImage',
            new_name='CaseStudyGalleryImage',
        ),
    ]
